Rebase, fix conflicts, update changelog etc. of several pending PR (#454)
* Update installation command to Helm v3

The previous command results in

```
Error: unknown flag: --name
```

See: https://stackoverflow.com/questions/57961162/helm-install-unknown-flag-name

* add containerSecurityContext

* Fix typo

* Fix typos in templates

* Support site configuration in operator helm chart

* Add changelog entry

* Specify US1 site in config comments

* Fix port number for datadog.apm.portEnabled option

* Fixed typo in datadog.apm.portEnabled description

* Update charts/datadog-operator/values.yaml to add a link to the site documentation

Co-authored-by: Cedric Lamoriniere <cedric.lamoriniere@datadoghq.com>

Co-authored-by: Charney Kaye <charneykaye@users.noreply.github.com>
Co-authored-by: kskumgk63 <keisuke.umegaki.630@gmail.com>
Co-authored-by: Chae SeungWoo <cotmddn4@gmail.com>
Co-authored-by: khewonc <caroline.kim@datadoghq.com>
Co-authored-by: Josh Garduna <josh.garduna@dealerware.com>
Co-authored-by: Cedric Lamoriniere <cedric.lamoriniere@datadoghq.com>