Update _helpers.tpl
The include function call is split across two lines, which Go templates do NOT allow and is treated as an unclosed action, hence the “unclosed action” meltdown from Helm. This was causing issue in datadog helm deployment with error 

Error: UPGRADE FAILED: parse error at (datadog/templates/_helpers.tpl:540): unclosed action helm.go:81: [debug] parse error at (datadog/templates/_helpers.tpl:540): unclosed action